[functions]
  external_node_modules = ["express", "@libsql/client"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = ["/api/*", "/:site"]
  status = 200
  to = "/.netlify/functions/api/:splat"